myhome/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('rosetta/', include('rosetta.urls')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('cities/', include('citiesapp.urls', namespace='city')),
    path('', include('properties.urls', namespace='property')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views


app_name = "profile"
urlpatterns = [
    path('create_user/', views.CreateUser.as_view(), name='create'),
    path('update_profile/<int:user_id>/', views.ProfileUpdate.as_view(), name='update'),
    path('edit_profile/<int:user_id>/', views.ProfileEdit.as_view(), name='edit'),
    path('edit_photo/<int:user_id>/', views.ProtoEdit.as_view(), name='photo'),
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from account.validators import validate_phone


class Profile(models.Model):
    MALE = 'MA'
    FEMALE = 'FE'
    OTHER = 'OT'
    GENDER = [
        (MALE, _('Male')),
        (FEMALE, _('Femele')),
        (OTHER, _('other')),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.BigIntegerField(null=True, validators=[validate_phone])
    nickname = models.CharField(_('Nickname'), max_length=20, default="none")
    gender = models.CharField(_('gender'), max_length=2, choices=GENDER, default=OTHER)
    city = models.CharField(_('city'), max_length=30, null=True, blank=True)
    photo = models.ImageField(upload_to="media/profiles", default="/profiles/profile.jpg")
    company = models.CharField(_('company'), max_length=30, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('account:login')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance).save()


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

properties/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from account.validators import validate_phone
from citiesapp.models import City, State


def current_year():
    return datetime.today().year


def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


def code_generator():
    last_property = Property.objects.all().order_by('id').last()
    # check if it is the first register
    if not last_property:
        code_str = datetime.now().strftime("%y") + datetime.now().strftime("%m") + '0000'
        code = int(code_str)
        return code
    # get letest property's code
    property_code = str(last_property.code)
    code_date = property_code[:4]
    code_unique = (int(property_code[-4:]))
    today_date = datetime.now().strftime("%y%m")
    # creates new code
    if code_date != today_date:
        code_str = today_date + '0000'
        code = int(code_str)
    else:
        code_unique_new = str(code_unique + 1).zfill(4)
        code_str = today_date + code_unique_new
        code = int(code_str)
    return code


class Project(models.Model):
    manager = models.ForeignKey(User, on_delete=models.CASCADE, related_name='projects', verbose_name=_('manager'))
    name = models.CharField(_('name'), max_length=30)
    name_slug = models.CharField(max_length=50)
    date_start = models.DateField(_('Beginning date'))
    date_complete = models.DateField(_('completion date'))
    photo = models.ImageField(upload_to="media/project", default="/profiles/project.jpg")
    facilities = models.ManyToManyField('Facility', related_name='projects', verbose_name=_('Facilities'))
    description = models.TextField(max_length=255, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.name_slug:
            self.name_slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)


class Facility(models.Model):
    name = models.CharField(max_length=40)
    name_slug = models.CharField(max_length=60)

    def save(self, *args, **kwargs):
        if not self.name_slug:
            self.name_slug = slugify(self.name)
        super(Facility, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Property(models.Model):
    APARTMENT = 'APT'
    HOUSE = 'HOU'
    LAND = 'LAN'
    COMMERCIAL = 'COM'
    FARM = 'FAR'

    NEW = 'NEW'
    OFFPLAN = 'PLA'
    STARTED = 'STA'
    USED = 'USE'

    TIPO_PRO = [
        (APARTMENT, _('apartment')),
        (HOUSE, _('house')),
        (LAND, _('land')),
        (FARM, _('farm')),
        (COMMERCIAL, _('commercial')),
    ]
    STATUS_PRO = [
        (NEW, _('new')),
        (OFFPLAN, _('off-plans')),
        (STARTED, _('on construction')),
        (USED, _('used')),
    ]

    code = models.IntegerField(_('code'), default=00000000)
    upload_code = models.IntegerField(_('upload-code'), default=00000000, null=True, blank=True)
    manager = models.ForeignKey(User, on_delete=models.CASCADE, related_name='properties', verbose_name=_('manager'))
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='my_properties', verbose_name=_('owner'))
    type_property = models.CharField(_('type of property'), max_length=70, choices=TIPO_PRO, default=APARTMENT)
    condition = models.CharField(_('condition'), max_length=40, choices=STATUS_PRO, default=NEW)
    price = models.DecimalField(_('price'), decimal_places=0, max_digits=12)
    price_str = models.CharField(max_length=18, default="")
    rooms = models.IntegerField(_('rooms'), default=0)
    baths = models.IntegerField(_('bathrooms'), default=0)
    parking = models.IntegerField(_('parking'), default=0)
    area_built = models.DecimalField(_('built area'), default=0, decimal_places=0, max_digits=12)
    area_total = models.DecimalField(_('total area'), default=0, decimal_places=0, max_digits=12)
    estrato = models.IntegerField(null=True, blank=True)
    year = models.PositiveIntegerField(_('built in'), default=current_year(),
                                       validators=[MinValueValidator(1900), max_value_current_year])
    title = models.CharField(_('title'), max_length=30)
    title_slug = models.SlugField(max_length=50)
    description = models.TextField(_('description'), max_length=700)
    type_business = models.ManyToManyField('BusinessType', related_name='business', verbose_name=_('offer type'))

    # analytic
    seen = models.IntegerField(_('seen'), default=0)
    active = models.BooleanField(_('active'), default=False)
    pause = models.BooleanField(_('pause'), default=False)
    promoted = models.BooleanField(_('promoted'), default=False)
    followers = models.ManyToManyField(User, through='Following', related_name='following', )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # project
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='proj_properties',
                                verbose_name=_('project'), null=True, blank=True)

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = "properties"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.title_slug:
            self.title_slug = slugify(self.title)
        if not self.code:
            self.code = code_generator()
        super(Property, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('property:detail', args=[self.id])


class AddressCol(models.Model):
    propiedad = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='address_col')
    departamento = models.ForeignKey(State, on_delete=models.SET_NULL, null=True, blank=True)
    ciudad = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    barrio = models.CharField(max_length=30, null=True, blank=True)
    tipo_via = models.CharField(max_length=30)
    via = models.CharField(max_length=30)
    prefijo_via = models.CharField(max_length=10, null=True, blank=True)
    numero = models.IntegerField()
    prefijo_numero = models.CharField(max_length=10, null=True, blank=True)
    placa = models.IntegerField()
    mostrar = models.BooleanField(default=False)

    def __str__(self):
        if self.mostrar:
            address = "{} {}{} # {}{} - {}, {}, {}".format(self.tipo_via, self.via,
                                                           self.prefijo_via, self.numero,
                                                           self.prefijo_numero, self.placa,
                                                           self.ciudad, self.departamento)
            return address.replace("None", "")
        else:
            if self.barrio:
                return "{}, {}, {}".format(self.barrio, self.ciudad, self.departamento)
            return "{}, {}".format(self.ciudad, self.departamento)


class Following(models.Model):
    user = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    property_followed = models.ForeignKey(Property, related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user, self.property_followed)


class BusinessType(models.Model):
    SALE = 'SALE / VENTA'
    RENT = 'RENT / ARRENDAMIENTO'
    SWAP = 'SWAP / PERMUTA'

    TIPO_BUS = [
        (SALE, _('sale')),
        (RENT, _('rent')),
        (SWAP, _('swap')),
    ]
    name = models.CharField(_('type of business'), max_length=70, choices=TIPO_BUS, default=SALE)

    def __str__(self):
        return self.name


class Image(models.Model):
    propiedad = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='gallery')
    image = models.ImageField(upload_to='img/', default='img/img_1.jpg', null=True, blank=True)
    main = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.propiedad.gallery.all():
            self.main = True
        super(Image, self).save(*args, **kwargs)


class Contact(models.Model):
    propiedad = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='contacts')
    name = models.CharField(_('name'), max_length=50)
    email = models.EmailField(_('email'), max_length=100, null=True, blank=True)
    phone = models.BigIntegerField(_('phone'), validators=[validate_phone])
    message = models.TextField(_('message'), max_length=500, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.utils.translation import gettext

class UserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args,**kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email')

    def clean_username(self):
        user = self.cleaned_data['username']
        usernames = [users.user.username for users in Profile.objects.all()]
        if user in usernames:
            self.add_error('username', gettext("Username is already taken"))
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        emails = [users.user.email for users in Profile.objects.all()]
        if email != "" and email in emails:
            self.add_error('email', gettext("Email is already registered"))
        return email


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'gender', 'city', 'company', 'photo')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'gender', 'city', 'company')


class ProfilePhotoForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('photo',)

profiles/views.py
from django.contrib.auth.models import User
import json
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from .forms import UserForm, ProfileForm, ProfileEditForm, ProfilePhotoForm
from .models import Profile


class CreateUser(CreateView):
    form_class = UserForm
    template_name = "profiles/create.html"


class ProfileUpdate(UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "profiles/profile.html"
    pk_url_kwarg = 'user_id'
    context_object_name = 'profile'

    def form_valid(self, form):
        form.save()
        return render(self.request, 'account/dashboard.html')

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the profile id
        context['pro_id'] = self.kwargs['user_id']
        return context


class ProfileEdit(UpdateView):
    model = Profile
    form_class = ProfileEditForm
    template_name = "profiles/edit.html"
    pk_url_kwarg = 'user_id'
    context_object_name = 'profile'

    def form_valid(self, form):
        form.save()
        return render(self.request, 'profiles/details_list.html')


class ProtoEdit(UpdateView):
    model = Profile
    form_class = ProfilePhotoForm
    template_name = "profiles/photo_edit.html"
    pk_url_kwarg = 'user_id'
    context_object_name = 'profile'

    def form_valid(self, form):
        form.save()
        return HttpResponse(json.dumps(0), content_type='application/json')





# def edit_profile(request):
#     form = ProfileEditForm(request.POST or None)
#     if request.method == 'POST':
#         form = ProfileEditForm(request.POST)
#         if form.is_valid():
#             form.save()
#             HttpResponse(json.dumps(0), content_type='application/json')
#         else:
#             render(request, "properties/edit.html", {'form': form})
#     render(request, "properties/edit.html", {'form': form})

profiles/templates/profiles/create.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new user</title>
    <style>
        li {
            text-align: center;
            font-size: 0.8rem;
            color: red;
         }
    </style>
</head>
<body>
     <form id="formulario2" action="{% url 'profile:create' %}" method="post">{% csrf_token %}
      <label>
        <span>{% trans 'Username' %}</span>
        {{ form.username }}
      </label>
         {{form.username.errors}}
         <label>
        <span>{% trans 'First Name' %}</span>
        {{ form.first_name }}
      </label>
         {{form.first_name.errors}}
         <label>
        <span>{% trans 'Last Name' %}</span>
        {{ form.last_name }}
      </label>
         {{form.last_name.errors}}
         <label>
        <span>{% trans 'Email' %}</span>
        {{ form.email }}
      </label>
         {{form.email.errors}}
         <label>
        <span>{% trans 'Password' %}</span>
        {{ form.password1 }}
      </label>
         {{form.password1.errors}}
         <label>
        <span>{% trans 'Confirm Password' %}</span>
        {{ form.password2 }}
      </label>
         {{form.password2.errors}}
         {{ form.non_field_errors }}
      <button type="button" onclick="sendForm()" class="submit" >{% trans 'sign up' %}</button>
<!--      <button type="button" class="fb-btn">Join with <span>facebook</span></button>-->
     </form>
</body>
</html>

profiles/templates/profiles/details_list.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>details</title>
</head>
<body>
    <div class="card-content white-text" style="word-wrap: break-word;">
        <div class="row">
            <div class="col s12 m6">
                <h6>{% trans 'Phone' %}</h6>
                <h4>{{user.profile.phone}}</h4>
            </div>
            <div class="col s12 m6">
                <h6>{% trans 'Gender' %}</h6>
                <h4>{{user.profile.gender}}</h4>
            </div>
        </div>
        <div class="row">
          <div class="col s12 m6">
              <h6>{% trans 'City' %}</h6>
              <h4>{{user.profile.city}}</h4>
          </div>
            <div class="col s12 m6">
                <h6>{% trans 'Company' %}</h6>
                <h4>{{user.profile.company}}</h4>
            </div>
        </div>
    </div>
</body>
</html>

profiles/templates/profiles/edit.html
{% load i18n %}
{% load static %}

    <form id="formulario" method="POST" action="">
        <div class="card-content white-text" style="word-wrap: break-word; margin:0;">{% csrf_token %}
            <div class="row">
                <div class="input-field col s12 m6">
                    {{form.phone}}
                    <label  style="font-size:1.2rem;">{{form.phone.label}}</label>
                    <span class="helper-text" data-error="wrong" data-success="right">{{form.phone.errors}}</span>

                </div>
                <div class="input-field col s12 m6">
                    {{form.city}}
                    <label style="font-size:1.2rem;">{{form.city.label}}</label>
                    <span class="helper-text" data-error="wrong" data-success="right">{{form.city.errors}}</span>

                </div>
            </div>
            <div class="row">
              <div class="input-field col s12 m6">
                  {{form.gender}}
                <label>{{form.gender.label}}</label>
                <span class="helper-text" data-error="wrong" data-success="right">{{form.gender.errors}}</span>
              </div>
                <div class="input-field col s12 m6">
                    {{form.company}}
                    <label  style="font-size:1.2rem;">{{form.company.label}}</label>
                <span class="helper-text" data-error="wrong" data-success="right">{{form.company.errors}}</span>
                </div>
            </div>
            <button  type="button" onclick="sendForm()">{% trans 'save' %}</button>
        </div>
        <br>
    </form>

profiles/templates/profiles/photo_edit.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>photo_edit</title>
    <link rel="stylesheet" type="text/css" href="{% static '/materialize/css/materialize.min.css' %}">
    <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
</head>
<body>
    <div class="row">
        <div class="left card-title">
            <b>{% trans 'Change Profile Photo' %}</b>
        </div>
    </div>
    <div class="row">
        <div   class="row">
            <form id="formulario2" method="post">{% csrf_token %}
                <div class="col s12">
                    <div class="card-panel grey lighten-5 z-depth-1">
                        <div class="row valign-wrapper">
                            <div id="id_image" class="col s3">
                                <img src="{{form.instance.photo.url}}" alt="profile" class="responsive-img"> <!-- notice the "circle" class -->
                            </div>
                            <div class="col s9">
                                {{ form.photo }}
                                {{form.photo.errors}}
                            </div>
                        </div>
                    </div>`
                </div>
                <button  type="button" onclick="sendForm2()" class="submit" >{% trans 'Confirm' %}</button>
            </form>
        </div>
    </div>

</body>
</html>

profiles/templates/profiles/profile.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%trans 'Edit Profile' %}</title>
    <style>
    li {
            text-align: center;
            font-size: 0.8rem;
            color: red;
    }

    </style>
    <!--    materialize-->
    <link rel="stylesheet" type="text/css" href="{% static '/materialize/css/materialize.min.css' %}">
    <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
    <!--    materialize-->
    <link rel="stylesheet" type="text/css" href="{% static '/style_login.css' %}">
<!--    &lt;!&ndash; Compiled and minified CSS &ndash;&gt;-->
<!--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">-->

<!--    &lt;!&ndash; Compiled and minified JavaScript &ndash;&gt;-->
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>-->

</head>
<body>

    <form id="formulario3" method="post">
    <span hidden id="url" >{% url 'profile:update' pro_id %}</span>
        <div class="col s12 m8 offset-m2 l6 offset-l3">
            <div class="card-panel grey lighten-5 z-depth-1">
                <div class="row valign-wrapper">
                    <div id="id_image" class="col s3">
                        <img  src="{{form.instance.photo.url}}"alt="" class="responsive-img"> <!-- notice the "circle" class -->
                    </div>
                    <div class="col s9">
                        {{ form.photo }}
                        {{form.photo.errors}}
                    </div>
                  </div>
            </div>
        </div>

        {% csrf_token %}
        <input hidden name="user_id" value="{{ pro_id }}">
        <label>
            <span>{% trans 'Phone' %}</span>
            {{ form.phone }}
            {{form.phone.errors}}
        </label>
        <label>
        <span>{% trans 'Gender' %}</span>
            {{ form.gender }}
            {{form.gender.errors}}
        </label>
        <label>
        <span>{% trans 'City' %}</span>
            {{ form.city }}
            {{form.city.errors}}
        </label>
        <label>
        <span>{% trans 'Company' %}</span>
            {{ form.company }}
            {{form.company.errors}}
        </label>
        {{ form.non_field_errors }}
        <button  type="button" onclick="sendForm3()" class="submit" >{% trans 'sign in now' %}</button>
    </form>
</body>

</html>