myhome/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('rosetta/', include('rosetta.urls')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('cities/', include('citiesapp.urls', namespace='city')),
    path('', include('properties.urls', namespace='property')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.utils.translation import gettext_lazy as _

from .views import TemplateView

app_name = "property"
urlpatterns = [
    path('', views.ListProperty.as_view(), name='index'),
    path('template/', views.Template, name='template'),
    path('home/', views.homepage, name='home'),
    path('new_property/', views.CreateProperty.as_view(), name='create'),
    path('new_project/', views.CreateProject.as_view(), name='create-project'),
    path('contact_us/', views.contact_us, name='contact'),
    path('property/upload', views.property_upload, name='upload'),
    path('property/follow', views.property_following, name='follow'),
    path('new_address_col/<int:prop_id>/', views.create_address, name='create-address'),
    path('new_image/<int:prop_id>/', views.create_image, name='create-image'),
    path('update_property/<int:pk>/', views.UpdateProperty.as_view(), name='update'),
    path('pause_property/<int:prop_id>/', views.pause, name='pause'),
    path('property_detail/<int:prop_id>/', views.property_detail, name='detail'),
    path('whatsapp_connect/', views.whatsapp_contact, name='whatsapp'),
    path('address/', TemplateView.as_view(template_name="properties/address_auto.html")),
    path('testing/', TemplateView.as_view(template_name="properties2/base.html")),
]

properties/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from account.validators import validate_phone
from citiesapp.models import City, State


def current_year():
    return datetime.today().year


def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


def code_generator():
    last_property = Property.objects.all().order_by('id').last()
    # check if it is the first register
    if not last_property:
        code_str = datetime.now().strftime("%y") + datetime.now().strftime("%m") + '0000'
        code = int(code_str)
        return code
    # get letest property's code
    property_code = str(last_property.code)
    code_date = property_code[:4]
    code_unique = (int(property_code[-4:]))
    today_date = datetime.now().strftime("%y%m")
    # creates new code
    if code_date != today_date:
        code_str = today_date + '0000'
        code = int(code_str)
    else:
        code_unique_new = str(code_unique + 1).zfill(4)
        code_str = today_date + code_unique_new
        code = int(code_str)
    return code


class Project(models.Model):
    manager = models.ForeignKey(User, on_delete=models.CASCADE, related_name='projects', verbose_name=_('manager'))
    name = models.CharField(_('name'), max_length=30)
    name_slug = models.CharField(max_length=50)
    date_start = models.DateField(_('Beginning date'))
    date_complete = models.DateField(_('completion date'))
    photo = models.ImageField(upload_to="media/project", default="/profiles/project.jpg")
    facilities = models.ManyToManyField('Facility', related_name='projects', verbose_name=_('Facilities'))
    description = models.TextField(max_length=255, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.name_slug:
            self.name_slug = slugify(self.name)
        super(Project, self).save(*args, **kwargs)


class Facility(models.Model):
    name = models.CharField(max_length=40)
    name_slug = models.CharField(max_length=60)

    def save(self, *args, **kwargs):
        if not self.name_slug:
            self.name_slug = slugify(self.name)
        super(Facility, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Property(models.Model):
    APARTMENT = 'APT'
    HOUSE = 'HOU'
    LAND = 'LAN'
    COMMERCIAL = 'COM'
    FARM = 'FAR'

    NEW = 'NEW'
    OFFPLAN = 'PLA'
    STARTED = 'STA'
    USED = 'USE'

    TIPO_PRO = [
        (APARTMENT, _('apartment')),
        (HOUSE, _('house')),
        (LAND, _('land')),
        (FARM, _('farm')),
        (COMMERCIAL, _('commercial')),
    ]
    STATUS_PRO = [
        (NEW, _('new')),
        (OFFPLAN, _('off-plans')),
        (STARTED, _('on construction')),
        (USED, _('used')),
    ]

    code = models.IntegerField(_('code'), default=00000000)
    upload_code = models.IntegerField(_('upload-code'), default=00000000, null=True, blank=True)
    manager = models.ForeignKey(User, on_delete=models.CASCADE, related_name='properties', verbose_name=_('manager'))
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='my_properties', verbose_name=_('owner'))
    type_property = models.CharField(_('type of property'), max_length=70, choices=TIPO_PRO, default=APARTMENT)
    condition = models.CharField(_('condition'), max_length=40, choices=STATUS_PRO, default=NEW)
    price = models.DecimalField(_('price'), decimal_places=0, max_digits=12)
    price_str = models.CharField(max_length=18, default="")
    rooms = models.IntegerField(_('rooms'), default=0)
    baths = models.IntegerField(_('bathrooms'), default=0)
    parking = models.IntegerField(_('parking'), default=0)
    area_built = models.DecimalField(_('built area'), default=0, decimal_places=0, max_digits=12)
    area_total = models.DecimalField(_('total area'), default=0, decimal_places=0, max_digits=12)
    estrato = models.IntegerField(null=True, blank=True)
    year = models.PositiveIntegerField(_('built in'), default=current_year(),
                                       validators=[MinValueValidator(1900), max_value_current_year])
    title = models.CharField(_('title'), max_length=30)
    title_slug = models.SlugField(max_length=50)
    description = models.TextField(_('description'), max_length=700)
    type_business = models.ManyToManyField('BusinessType', related_name='business', verbose_name=_('offer type'))

    # analytic
    seen = models.IntegerField(_('seen'), default=0)
    active = models.BooleanField(_('active'), default=False)
    pause = models.BooleanField(_('pause'), default=False)
    promoted = models.BooleanField(_('promoted'), default=False)
    followers = models.ManyToManyField(User, through='Following', related_name='following', )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # project
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='proj_properties',
                                verbose_name=_('project'), null=True, blank=True)

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = "properties"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.title_slug:
            self.title_slug = slugify(self.title)
        if not self.code:
            self.code = code_generator()
        super(Property, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('property:detail', args=[self.id])


class AddressCol(models.Model):
    propiedad = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='address_col')
    departamento = models.ForeignKey(State, on_delete=models.SET_NULL, null=True, blank=True)
    ciudad = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    barrio = models.CharField(max_length=30, null=True, blank=True)
    tipo_via = models.CharField(max_length=30)
    via = models.CharField(max_length=30)
    prefijo_via = models.CharField(max_length=10, null=True, blank=True)
    numero = models.IntegerField()
    prefijo_numero = models.CharField(max_length=10, null=True, blank=True)
    placa = models.IntegerField()
    mostrar = models.BooleanField(default=False)

    def __str__(self):
        if self.mostrar:
            address = "{} {}{} # {}{} - {}, {}, {}".format(self.tipo_via, self.via,
                                                           self.prefijo_via, self.numero,
                                                           self.prefijo_numero, self.placa,
                                                           self.ciudad, self.departamento)
            return address.replace("None", "")
        else:
            if self.barrio:
                return "{}, {}, {}".format(self.barrio, self.ciudad, self.departamento)
            return "{}, {}".format(self.ciudad, self.departamento)


class Following(models.Model):
    user = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    property_followed = models.ForeignKey(Property, related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user, self.property_followed)


class BusinessType(models.Model):
    SALE = 'SALE / VENTA'
    RENT = 'RENT / ARRENDAMIENTO'
    SWAP = 'SWAP / PERMUTA'

    TIPO_BUS = [
        (SALE, _('sale')),
        (RENT, _('rent')),
        (SWAP, _('swap')),
    ]
    name = models.CharField(_('type of business'), max_length=70, choices=TIPO_BUS, default=SALE)

    def __str__(self):
        return self.name


class Image(models.Model):
    propiedad = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='gallery')
    image = models.ImageField(upload_to='img/', default='img/img_1.jpg', null=True, blank=True)
    main = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.propiedad.gallery.all():
            self.main = True
        super(Image, self).save(*args, **kwargs)


class Contact(models.Model):
    propiedad = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='contacts')
    name = models.CharField(_('name'), max_length=50)
    email = models.EmailField(_('email'), max_length=100, null=True, blank=True)
    phone = models.BigIntegerField(_('phone'), validators=[validate_phone])
    message = models.TextField(_('message'), max_length=500, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

properties/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext
from .models import Property, AddressCol, Image, Contact, BusinessType, Project
from .validators import TIPO_PRO, TIPO_BUS, STATUS_PRO
import string

PREFIJOS = [tuple([x, x]) for x in string.ascii_uppercase[:8]]
[PREFIJOS.append(tuple(['{} BIS'.format(x), '{} BIS'.format(x)])) for x in string.ascii_uppercase[:8]]
PREFIJOS.append(tuple(['SUR', 'SUR']))
[PREFIJOS.append(tuple(['{} SUR'.format(x), '{} SUR'.format(x)])) for x in string.ascii_uppercase[:8]]
PREFIJOS.insert(0, tuple(['', '']))

VIAS = [
    ('CL', 'Calle'),
    ('CR', _('Carrera')),
    ('TV', _('Transversal')),
    ('DG', _('Diagonal')),
    ('AV', _('Avenida')),
    ('AC', _('Avenida calle')),
    ('AK', _('Avenida carrera')),
]


class ProjectForm(forms.ModelForm):
    """Form for new project"""
    properties = forms.ModelMultipleChoiceField(queryset=Property.objects.all())
    photo2 = forms.ImageField()
    photo3 = forms.ImageField()

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)

    class Meta:
        model = Project
        exclude = ['name_slug', 'manager']


class PropertyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        manager = kwargs.pop('manager')
        super().__init__(*args, **kwargs)

        self.fields['project'] = forms.ModelChoiceField(Project.objects.filter(manager=manager))
        self.fields['project'].required = False
        self.fields['description'].widget.attrs.update(rows='6', cols='85')
        self.fields['description'].widget.attrs['placeholder'] = \
            gettext("Add extra information that adds value to your property."
                    " i.e. common areas, services, security, location, etc.")
        self.fields['owner'].empty_label = _('select owner')
        # self.fields['owner'].widget.attrs['disabled'] = True
        self.fields['price_str'].label = _('price')

    class Meta:
        model = Property
        exclude = ['title_slug', 'code', 'seen', 'active', 'followers', 'manager', 'upload_code', 'promoted', 'pause']


class AddressColForm(forms.ModelForm):
    prefijo_via = forms.CharField(widget=forms.Select(choices=PREFIJOS), required=False)
    prefijo_numero = forms.CharField(widget=forms.Select(choices=PREFIJOS), required=False)
    tipo_via = forms.CharField(widget=forms.Select(choices=VIAS), required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tipo_via'].widget.attrs.update(placeholder='ej. Calle')
        self.fields['via'].widget.attrs.update(placeholder='ej. 10')
        # self.fields['prefijo_via'].widget.attrs.update(empty_label='ej. A',)
        self.fields['numero'].widget.attrs.update(placeholder='ej. 11')
        self.fields['prefijo_numero'].widget.attrs.update(placeholder='ej. BIS')
        self.fields['placa'].widget.attrs.update(placeholder='ej. 12')
        self.fields['ciudad'].widget.attrs.update(placeholder='ej. Bogota')
        self.fields['departamento'].widget.attrs.update(placeholder='ej. Cundinamarca')
        self.fields['departamento'].empty_label = "Departamento"
        self.fields['ciudad'].empty_label = "Ciudad"
        self.fields['barrio'].widget.attrs.update(placeholder='ej. Cedritos', required=False)
        self.fields['prefijo_via'].label = 'prefijo'
        self.fields['prefijo_numero'].label = 'prefijo'

    class Meta:
        model = AddressCol
        exclude = []


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        exclude = ['propiedad']


class ContactForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update(rows='4', cols='25')

    class Meta:
        model = Contact
        fields = ['name', 'phone', 'email', 'message']


class MultiPropForm(forms.Form):
    csv_file = forms.FileField(label=_('csv file'))
    owner = forms.ModelChoiceField(queryset=User.objects.all())


# *********New style forms***********"""


class SearchBarForm(forms.Form):
    """Index main search bar form inputs"""
    business_type = forms.ChoiceField(choices=TIPO_BUS)
    property_type = forms.ChoiceField(choices=TIPO_PRO)
    property_condition = forms.ChoiceField(choices=STATUS_PRO)
    city = forms.CharField(max_length=127, required=False)
    state = forms.CharField(max_length=127, required=False)
    locality = forms.CharField(max_length=127, required=False)

properties/templates/properties/base_new.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{% endblock %}</title>
    <!--ajax.js-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!--ajax.js-->

    <!--animate.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
     <!--animate.css-->
    <!--fontawesome-->
    <link href="{% static 'css/fontawesome-free-5.11.2-web/css/all.css' %}" rel='stylesheet'/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--fontawesome-->

    <!--JQUERY STEPS--->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.steps.css' %}">
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
    <script src="{% static 'js/jquery.steps.js' %}"></script>
    <!--JQUERY STEPS--->

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!--ajax.css-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <!--ajax.css-->

    <!--BOOTSTRAP-->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
     <!--BOOTSTRAP-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-158817582-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-158817582-1');
    </script>
    {% block styles %}
    {% endblock %}
</head>
<body>
{% block body %}
{% block scripts %}
{% endblock %}
{% endblock %}
</body>
</html>

properties/templates/properties/contact_email.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en" class="body-full-height">

<head>
    <!-- META SECTION -->
    <title>Email Contact</title>
   
   <style>
       .card {
          position: relative;
          margin: .5rem 0 1rem 0;
          background-color:white;
          -webkit-transition: -webkit-box-shadow .25s;
          transition: -webkit-box-shadow .25s;
          transition: box-shadow .25s;
          transition: box-shadow .25s, -webkit-box-shadow .25s;
          border-radius: 2px;
      }
   </style>
</head>

<body>
<div align="center">
<div style="padding: 15px;width: 90%; height:150px;box-shadow: 0px 3px 9px 5px rgba(0,0,0,0.75);" align="center" class="card">
  <div style="text-align: left;width: 100%;">
    <h2>Cliente Interesado</h2>
  </div>

  <div style="background-color: #eee !important;width: 60%;float: left;margin-left:2%; margin-right: 4%;">
      <div style="text-align: center;">
         <table style="width:100%">
          <tr>
            <th>Nombre</th>
            <th>Email</th>
            <th>Telefono</th>
          </tr>
          <tr>
            <td>{{data.name}}</td>
            <td>{{data.email}}</td>
            <td>{{data.phone}}</td>
          </tr>
        </table>
      </div>
      <p class="color">Mensaje:&nbsp;&nbsp;<a style="font-size: 11px;">{{data.message}}</a></p>
  </div>

  <div style="width: 30%; float: left;">
    <a href="https://api.whatsapp.com/send?phone=+57{{data.phone}}&text=Hola%20{{data.name}}%2C%20quieres%20mas%20informacion%20sobre%20el%20inmueble%20{{data.propiedad.title}}%2C%20ubicado%20en%20%3A%20{{data.addr_parse}}%3F%20Enlace%3A%20Inmueblesfusa.com/property_detail/{{data.propiedad.id}}">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTF-52JbMRNbBkkd_2z6yjU_0xD-7ygQ9I9Wu7GN9MScDhQD04L&s"  width="100" height="100">
    </a>
  </div>
</div>
<br>
<div style=" padding: 15px;width: 90%;height: 600px; box-shadow: 0px 3px 9px 5px rgba(0,0,0,0.75)" align="center" class="card">
 {% with address=data.propiedad.address_col.get %}
  <div style="text-align: left;width: 100%;">
    <h2>{{data.propiedad.title}}</h2>
  </div>

  <div style="width: 50%;float: left;margin-left:2%;margin-right: 4%;background-color: #eee !important;">
      <div style="text-align: center;">
         <img src="cid:{{data.image}}" width="100%" height="250">
      </div>
      {{address}}
       <br/>
     <div style="text-align: left;padding-bottom: 1%;margin:9px;">
       {{data.propiedad.description}}
     </div>
  </div>
  <div style="width: 40%; float: left;background-color: #eee !important;">
    <div style="text-align: left;margin-left: 4%;">
      <p class="color"><strong>Tipo Propiedad: </strong>{{data.propiedad.type_property}}</p>
      <p class="color"><strong>Precio: </strong>{{data.propiedad.price}}</p>
      <p class="color"><strong>Habitaciones: </strong>{{data.propiedad.rooms}}</p>
      <p class="color"><strong>Baños: </strong>{{data.propiedad.baths}}</p>
      <p class="color"><strong>Estacionamiento: </strong>{{data.propiedad.parking}}</p>
      <p class="color"><strong>Área construida: </strong>{{data.propiedad.area_built}}</p>
      <p class="color"><strong>Área Total : </strong>{{data.propiedad.area_total}}</p>
      <p class="color"><strong>Éstrato: </strong>{{data.propiedad.estrato}}</p>
      <p class="color"><strong>Año: </strong>{{data.propiedad.year}}</p>
      <p class="color"><strong>Codigo: </strong>{{data.propiedad.code}}</p>
    </div>
  </div>
</div>
<div>
     <p  style="text-align: center; white-space: nowrap; font-size: 17px;font-weight: bold">Correo electrónico enviado autoamticamente. No responder. Preguntas o requerimientos, por favor contáctenos en xxxx@xxxxxxx.xxx!
      </p>
    </div>
 {% endwith %}
</div>
</body>
</html>

properties/templates/properties/contact_form.html
{% load i18n %}
<style>
    input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
/* Firefox */
input[type=number] {
  -moz-appearance:textfield;
}
input {
    width: 100%;
}
textarea {
  width: 100%;
}
</style>
<h3 class="h4 text-black widget-title mb-3">{% trans 'Contact Agent' %}</h3>
<form  id="idForm" class="form-contact-agent" method="post">{% csrf_token %}
    {% if form %}
        <div class="form-group">
          <label class="col-md-12 col-sm-12 col-xs-12 control-label">
            <i class="fas fa-id-card-alt"></i>&nbsp;{{form.name.label}}<span style="color:red;"> *</span></label>
          {{form.name}}
        </div>
        <div class="form-group">
          <label class="col-md-12 col-sm-12 col-xs-12 control-label">
            <i class="fas fa-phone-square-alt"></i>&nbsp;{{form.phone.label}}<span style="color:red;"> *</span></label>
          {{form.phone}}
        </div>
        <div class="form-group">
          <label class="col-md-12 col-sm-12 col-xs-12 control-label">
            <i class="fas fa-at"></i>&nbsp;{{form.email.label}}</label>
          {{form.email}}
        </div>
        <div class="form-group">
          <label class="col-md-12 col-sm-12 col-xs-12 control-label">
            <i class="fas fa-envelope"></i>&nbsp;{{form.message.label}}</label>
          {{form.message}}
        </div>
        {% if form.errors %}
            <div class="alert alert-info" style="font-weight: bold;">
              {{form.name.errors}}
              {{form.phone.errors}}
              {{form.email.errors}}
              {{form.message.errors}}
            </div>
        {% endif %}
        <div class="form-group">
          <input type="submit" id="phone" class="btn btn-primary" style="background-color:#364e68" value="{% trans 'Send Message' %}">
        </div>
    {% endif %}
    <p>{{mess}}</p>
</form>

properties/templates/properties/new_project.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>{% trans 'New Property' %}</title>
	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Main Style Css -->
	<link rel="stylesheet" href="{% static 'css/forms/style.css' %}"/>
</head>
<body>
	<div class="page-content" style="background-image: url('images/wizard-v3.jpg')">
<!--		<div class="wizard-v3-content">-->
<!--			<div class="wizard-form">-->
			                <div class="inner">
			                	<div class="form-row">
									<div class="form-holder form-holder-2">
										<label class="form-row-inner">
											<input type="text" class="form-control" id="cvc2" name="cvc3" required>
											<span class="label">{{form.name.label}}</span>
					  						<span class="border"></span>
										</label>
									</div>
								</div>
							</div>
	</div>
	<script src="{% static 'js/forms/jquery-3.3.1.min.js' %}"></script>
	<!-- Compiled and minified JavaScript -->
	<script>
		$(document).ready(function(){

			$("input,select").addClass('form-control');

			$("#id_date_start,#id_date_complete").focus( function () {
				this.type='date';
			});

			$("#id_date_start,#id_date_complete").blur( function () {
				this.type='text';
			});

			$("#id_facilities").attr('class','js-select-multiple form-control');

			$("#id_properties").attr('class','js-select-multiple form-control');
			$("#id_properties").attr('multiple','multiple');
			$('#id_properties').val(null).trigger('change');

			$('.js-select-multiple').select2();

			// Change image when photo is uploaded
			document.getElementById('id_photo').addEventListener('change', handleFileSelect, false);
			document.getElementById('id_photo2').addEventListener('change', handleFileSelect, false);
			document.getElementById('id_photo3').addEventListener('change', handleFileSelect, false);
		});

		function handleFileSelect(event) {
      		alert("got into function")
          	var files = event.target.files; // FileList object
          	// Loop through the FileList and render image files as thumbnails
          	for (var i = 0, f; f = files[i]; i++) {
              	// Only process image files
              	if (!f.type.match('image.*')) continue;
              	// Init FileReader()
              	// See: https://developer.mozilla.org/en-US/docs/Web/API/FileReader
              	var reader = new FileReader();
              	// Closure to capture the file information
              	reader.onload = (function () {
                  	return function (e) {
                  		let newImage = '<div class="column2" style="background-image:url('+e.target.result+')"\
											 title="'+e.target.result+'" onclick="myFunction(this);">\
											<i class="zmdi zmdi-aspect-ratio-alt zmdi-hc-2x"></i>\
										</div>'
						let imageDiv = document.
						getElementById('imageDiv');
						imageDiv.innerHTML += newImage;
                  	};
              })(f);
              // Read in the image file as a data URL
              reader.readAsDataURL(f);
			}
		}


		function loopImageFields(){
			$("#imageFields input[type=file]").each(function () {
				if (!$(this).val()){
					$(this).trigger('click');
				}
			});
		}


		function myFunction(imgs) {
		  	// Get the expanded image
		  	var expandImg = document.getElementById("expandedImg");
		  	// Get the image text
		  	var imgText = document.getElementById("imgtext");
		  	// Use the same src in the expanded image as the image being clicked on from the grid
		  	expandImg.src = imgs.title;
		 	 // Use the value of the alt attribute of the clickable image as text inside the expanded image
		 	 //imgText.innerHTML = imgs.title;
		  	// Show the container element (hidden with CSS)
		  	expandImg.parentElement.style.display = "block";
		  	expandImg.scrollIntoView()
		}
	</script>
</body>
</html>