myhome/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('rosetta/', include('rosetta.urls')),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('cities/', include('citiesapp.urls', namespace='city')),
    path('', include('properties.urls', namespace='property')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.utils.translation import gettext_lazy as _

from .views import TemplateView

app_name = "property"
urlpatterns = [
    path('', views.ListProperty.as_view(), name='index'),
    path('template/', views.Template, name='template'),
    path('home/', views.homepage, name='home'),
    path('new_property/', views.CreateProperty.as_view(), name='create'),
    path('new_project/', views.CreateProject.as_view(), name='create-project'),
    path('contact_us/', views.contact_us, name='contact'),
    path('property/upload', views.property_upload, name='upload'),
    path('property/follow', views.property_following, name='follow'),
    path('new_address_col/<int:prop_id>/', views.create_address, name='create-address'),
    path('new_image/<int:prop_id>/', views.create_image, name='create-image'),
    path('update_property/<int:pk>/', views.UpdateProperty.as_view(), name='update'),
    path('pause_property/<int:prop_id>/', views.pause, name='pause'),
    path('property_detail/<int:prop_id>/', views.property_detail, name='detail'),
    path('whatsapp_connect/', views.whatsapp_contact, name='whatsapp'),
    path('address/', TemplateView.as_view(template_name="properties/address_auto.html")),
    path('testing/', TemplateView.as_view(template_name="properties2/base.html")),
]

properties/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext
from .models import Property, AddressCol, Image, Contact, BusinessType, Project
from .validators import TIPO_PRO, TIPO_BUS, STATUS_PRO
import string

PREFIJOS = [tuple([x, x]) for x in string.ascii_uppercase[:8]]
[PREFIJOS.append(tuple(['{} BIS'.format(x), '{} BIS'.format(x)])) for x in string.ascii_uppercase[:8]]
PREFIJOS.append(tuple(['SUR', 'SUR']))
[PREFIJOS.append(tuple(['{} SUR'.format(x), '{} SUR'.format(x)])) for x in string.ascii_uppercase[:8]]
PREFIJOS.insert(0, tuple(['', '']))

VIAS = [
    ('CL', 'Calle'),
    ('CR', _('Carrera')),
    ('TV', _('Transversal')),
    ('DG', _('Diagonal')),
    ('AV', _('Avenida')),
    ('AC', _('Avenida calle')),
    ('AK', _('Avenida carrera')),
]


class ProjectForm(forms.ModelForm):
    """Form for new project"""
    properties = forms.ModelMultipleChoiceField(queryset=Property.objects.all())
    photo2 = forms.ImageField()
    photo3 = forms.ImageField()

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)

    class Meta:
        model = Project
        exclude = ['name_slug', 'manager']


class PropertyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        manager = kwargs.pop('manager')
        super().__init__(*args, **kwargs)

        self.fields['project'] = forms.ModelChoiceField(Project.objects.filter(manager=manager))
        self.fields['project'].required = False
        self.fields['description'].widget.attrs.update(rows='6', cols='85')
        self.fields['description'].widget.attrs['placeholder'] = \
            gettext("Add extra information that adds value to your property."
                    " i.e. common areas, services, security, location, etc.")
        self.fields['owner'].empty_label = _('select owner')
        # self.fields['owner'].widget.attrs['disabled'] = True
        self.fields['price_str'].label = _('price')

    class Meta:
        model = Property
        exclude = ['title_slug', 'code', 'seen', 'active', 'followers', 'manager', 'upload_code', 'promoted', 'pause']


class AddressColForm(forms.ModelForm):
    prefijo_via = forms.CharField(widget=forms.Select(choices=PREFIJOS), required=False)
    prefijo_numero = forms.CharField(widget=forms.Select(choices=PREFIJOS), required=False)
    tipo_via = forms.CharField(widget=forms.Select(choices=VIAS), required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tipo_via'].widget.attrs.update(placeholder='ej. Calle')
        self.fields['via'].widget.attrs.update(placeholder='ej. 10')
        # self.fields['prefijo_via'].widget.attrs.update(empty_label='ej. A',)
        self.fields['numero'].widget.attrs.update(placeholder='ej. 11')
        self.fields['prefijo_numero'].widget.attrs.update(placeholder='ej. BIS')
        self.fields['placa'].widget.attrs.update(placeholder='ej. 12')
        self.fields['ciudad'].widget.attrs.update(placeholder='ej. Bogota')
        self.fields['departamento'].widget.attrs.update(placeholder='ej. Cundinamarca')
        self.fields['departamento'].empty_label = "Departamento"
        self.fields['ciudad'].empty_label = "Ciudad"
        self.fields['barrio'].widget.attrs.update(placeholder='ej. Cedritos', required=False)
        self.fields['prefijo_via'].label = 'prefijo'
        self.fields['prefijo_numero'].label = 'prefijo'

    class Meta:
        model = AddressCol
        exclude = []


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        exclude = ['propiedad']


class ContactForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update(rows='4', cols='25')

    class Meta:
        model = Contact
        fields = ['name', 'phone', 'email', 'message']


class MultiPropForm(forms.Form):
    csv_file = forms.FileField(label=_('csv file'))
    owner = forms.ModelChoiceField(queryset=User.objects.all())


# *********New style forms***********"""


class SearchBarForm(forms.Form):
    """Index main search bar form inputs"""
    business_type = forms.ChoiceField(choices=TIPO_BUS)
    property_type = forms.ChoiceField(choices=TIPO_PRO)
    property_condition = forms.ChoiceField(choices=STATUS_PRO)
    city = forms.CharField(max_length=127, required=False)
    state = forms.CharField(max_length=127, required=False)
    locality = forms.CharField(max_length=127, required=False)

properties/views.py
import ast
import csv
import io
import os
import urllib
import json
from email.mime.image import MIMEImage
from smtplib import SMTPAuthenticationError

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMultiAlternatives, send_mail
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.translation import gettext
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.base import TemplateView
from geoservice.location import get_coordinates
from myhome import settings
from visits.visits import Visits
from .decorators import user_is_propertys_manager
from .forms import PropertyForm, AddressColForm, ContactForm, MultiPropForm, ProjectForm, SearchBarForm
from .models import Property, AddressCol, Image, Contact, BusinessType, Following, Project
from .validators import TIPO_PRO


class ListProperty(ListView):
    model = Property
    template_name = 'properties/index.html'
    paginate_by = 6

    def get(self, request, *args, **kwargs):
        # get data
        current_filters = request.GET.get('current_filters')
        filter_index = request.GET.get('remove')
        city = request.GET.get('select-city')
        follow = request.GET.get('follow')
        condition = request.GET.get('condition')
        filters_names = ['City', 'type_property', 'type_business__name', 'rooms__gte', 'rooms__lte', 'baths__gte',
                         'baths__lte', 'area_total__gte', 'area_total__lte', 'price__gte', 'price__lte', 'condition']
        # filter_names and filter values must have corresponding index, e.g. city's index == and select-city's index
        filters_values = [city, request.GET.get('list-types'), request.GET.get('offer-types'),
                          request.GET.get('room_min'), request.GET.get('room_max'), request.GET.get('bath_min'),
                          request.GET.get('bath_max'), request.GET.get('area_min'), request.GET.get('area_max'),
                          request.GET.get('price_min'), request.GET.get('price_max'), request.GET.get('condition')]

        filters_labels = {'select-city': gettext('City'), 'SALE / VENTA': {gettext('Offer Type'): gettext('Sale')},
                          'RENT / ARRENDAMIENTO': {gettext('Offer Type'): gettext('Rent')},
                          'SWAP / PERMUTA': {gettext('Offer Type'): gettext('Swap')},
                          'APT': {gettext('Property type'): gettext('Apartment')},
                          'HOU': {gettext('Property type'): gettext('House')},
                          'LAN': {gettext('Property type'): gettext('Land')},
                          'COM': {gettext('Property type'): gettext('Commercial')},
                          'FAR': {gettext('Property type'): gettext('Farm')},
                          'NEW': {gettext('Condition'): gettext('New')}, 'USE': {gettext('Condition'): gettext('Used')},
                          'PLA': {gettext('Condition'): gettext('Off-plan')},
                          'STA': {gettext('Condition'): gettext('On construction')}, 'rooms__gte': gettext('Min rooms'),
                          'rooms__lte': gettext('Max rooms'), 'baths__gte': gettext('Min bathrooms'),
                          'baths__lte': gettext('Max bathrooms'), 'area_total__gte': gettext('Min area'),
                          'area_total__lte': gettext('Max area'), 'price__gte': gettext('Min price'),
                          'price__lte': gettext('Max price'),
                          }
        # init variables
        query = self.model.objects.all().filter(active=True, pause=False)
        filters_dict = {}

        if current_filters:
            filters_dict = ast.literal_eval(current_filters)
            filters_dict.pop(list(filters_dict.items())[int(filter_index)][0])
            if 'City' in filters_dict:
                city = filters_dict['City']

        # assign data to filters
        new_filters = dict(zip(filters_names, filters_values))
        for key, value in new_filters.items():
            if value not in ['ALL', None, 'None']:
                filters_dict[key] = value

        # check if following action, otherwise assign filters to query
        if follow not in ['None', None]:
            if request.GET.get('prop_id'):  # if prop_id in request. it means following property action
                prop = Property.objects.get(id=request.GET.get('prop_id'))
                if request.user.is_authenticated:
                    user = self.request.user
                    if user.following.filter(id=prop.id):
                        user.following.remove(prop)
                        user.save()
                        print("{} stopped following {}".format(user, prop))
                        return HttpResponse(json.dumps({'command': 0, 'prop_id': prop.id}),
                                            content_type='application/json')
                    elif user != prop.manager:
                        follows = Following(user=user, property_followed=prop)
                        follows.save()
                        print("{} started following {}".format(user, prop))
                        return HttpResponse(json.dumps({'command': 1, 'prop_id': prop.id}),
                                            content_type='application/json')
                    else:
                        return HttpResponse(json.dumps({'command': 2, 'prop_id': prop.id}),
                                            content_type='application/json')
                else:
                    return HttpResponse(json.dumps({'command': -1, 'prop_id': -1}), content_type='application/json')

        elif filters_dict:
            filters_query = filters_dict.copy()
            filters_query.pop('City', None)
            query = self.model.objects.filter(**filters_query).filter(active=True, pause=False)

        # check location filter
        if city not in ['ALL', None]:
            prop_with_address = [prop for prop in query if prop.address_col.all()]
            query = [q for q in prop_with_address if q.address_col.get().ciudad.name == city]

        # assign labels
        filters_active = filters_dict.copy()
        for k, v in filters_dict.items():
            if v in filters_labels:
                filters_active.pop(k, None)
                filters_active[list(filters_labels[v].keys())[0]] = list(filters_labels[v].values())[0]
            elif k in filters_labels:
                filters_active[filters_labels[k]] = v
                filters_active.pop(k, None)

        # format price
        try:
            filters_active['Min price'] = "${:0,.0f}".format(int(filters_active['Min price'])).replace(',', '.')
        except KeyError:
            try:
                filters_active['Min precio'] = "${:0,.0f}".format(int(filters_active['Min precio'])).replace(',', '.')
            except KeyError:
                pass
        try:
            filters_active['Max price'] = "${:0,.0f}".format(int(filters_active['Max price'])).replace(',', '.')
        except KeyError:
            try:
                filters_active['Max precio'] = "${:0,.0f}".format(int(filters_active['Max precio'])).replace(',', '.')
            except KeyError:
                pass

        # format area
        try:
            filters_active['Min area'] = "{:0,.0f}m\u00b2".format(int(filters_active['Min area'])).replace(',', '.')
        except KeyError:
            try:
                filters_active['Min área'] = "{:0,.0f}m\u00b2".format(int(filters_active['Min área'])).replace(',', '.')
            except KeyError:
                pass
        try:
            filters_active['Max area'] = "{:0,.0f}m\u00b2".format(int(filters_active['Max area'])).replace(',', '.')
        except KeyError:
            try:
                filters_active['Max área'] = "{:0,.0f}m\u00b2".format(int(filters_active['Max área'])).replace(',', '.')
            except KeyError:
                pass

        # assign query and filters to context
        self.object_list = query
        context = self.get_context_data()
        context['filters'] = filters_dict
        context['filters_active'] = filters_active

        if not request.is_ajax():
            return self.render_to_response(context)
        return render(request, 'properties/property_list.html', context)


def property_following(request):
    if request.method == 'GET':
        print(request.GET.get('prop_id'))
        all_properties = Property.objects.all()
        try:
            user = request.user
            prop = Property.objects.get(id=request.GET.get('prop_id'))
        except:
            return HttpResponse(json.dumps(0), content_type='application/json')
        if user.following.filter(id=prop.id):
            user.following.remove(prop)
            user.save()
        else:
            follows = Following(user=user, property_followed=prop)
            follows.save()
        return render(request, 'properties/property_list.html', {'object_list': all_properties})


class CreateProject(CreateView):
    """Create new project"""
    model = Project
    template_name = 'properties/new_project.html'
    form_class = ProjectForm

    def get_success_url(self):
        return reverse_lazy('property:index')

    def form_invalid(self, form):
        print("form invalid \n")
        return super(CreateProject, self).form_invalid(form)

    def form_valid(self, form):
        print(form.cleaned_data)
        properties = form.cleaned_data.pop('properties', None)

properties/templates/properties2/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}

{% load sass_tags %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!--    BOOTSTRAP-->
    <link href="{% sass_src 'custom.scss' %}" rel="stylesheet" type="text/css" />
    <!--    FONT AWESOME-->
    <link href="{% static 'css/fontawesome-free-5.11.2-web/css/all.css' %}" rel='stylesheet'/>

    <!--    BASE STYLE-->
    <link rel="stylesheet" href="{% static 'css/myhome/base.css' %}"/>
    <!--    JQUERY-->
    {% block styles %}
    {% endblock %}

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.png'%}" width="40" height="40" alt="">
<!--            <img src="{% static 'project/logo.png'%}" width="50" height="50" alt="">-->
        </a>
        <a class="navbar-brand" href="#">{% trans 'My Home' %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse flex-grow-1 text-right" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto flex-nowrap">
                <li class="nav-item {% if page == 'home' %} active {% endif %}">
                    <a class="nav-link" href="#">{% trans 'Home' %}</a>
                </li>
                <li class="nav-item {% if page == 'login' %} active {% endif %}">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="#">{% trans 'Logout' %}</a>
                    {% else %}
                    <a class="nav-link" href="#">{% trans 'Login' %}</a>
                    {% endif %}
                </li>
                <li class="nav-item mx-1">
                    <button type="button" class="btn btn-secondary my-1">{% trans 'Publish' %}</button>
                </li>
            </ul>
            <div class="btn-group btn-group-sm mx-1" role="group" aria-label="Basic example">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <a  href="/{{ language.code }}" type="button" class="btn
                     {% if language.code == LANGUAGE_CODE  %}btn-primary{%else%} btn-secondary {% endif %}"
                        title="{{language.name_local|title}}">
                        {{ language.code|upper}}
                    </a>
                {% endfor %}
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
    <footer>
        <div class="col-md-12 text-center">
            <p>Made with love by My2home</p>
        </div>
    </footer>
</body>
</html>

properties/templates/properties2/index.html
{% extends 'properties2/base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
{% trans 'Home' %}
{% endblock %}

{% block styles %}
<!--    INDEX STYLE-->
<link rel="stylesheet" href="{% static 'css/myhome/index.css' %}"/>
{% endblock %}
{% block body %}
<div hidden>
    <!--    hidden input for form-->
    <form id="searchForm" method="post">{% csrf_token %}
        {{form.business_type}}
        {{form.property_type}}
        {{form.property_condition}}
        {{form.city}}
        {{form.state}}
        {{form.locality}}
    </form>
</div>

<div class="input-group col-lg-12  col-xl-10 offset-xl-1  col-md-12  col-sm-12 my-5">
    <div class="col-xm-12 col-sm-4 col-lg-3 mx-0 px-0">
        <button id="butBusiness" class="btn btn-outline-secondary btn-lg btn-block dropdown-toggle down-in-group1" type="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'Sale' %}
        </button>
        <div class="dropdown-menu col-sm-12 text-center">
            {% for choice in form.business_type.field.choices%}
            <a class="dropdown-item" onclick="selectBusinessType('{{choice.0}}')">{{choice.1}}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col-xm-12 col-sm-4 col-lg-3 mx-0 px-0">
        <button id="butProperty" class="btn btn-outline-secondary btn-lg  btn-block dropdown-toggle down-in-group2" type="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'Apartment' %}
        </button>
        <div class="dropdown-menu col-sm-12 text-center">
            {% for choice in form.property_type.field.choices%}
            <a class="dropdown-item" onclick="selectPropertyType('{{choice.0}}')">{{choice.1}}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-lg-2  mx-0 px-0">
        <button id="butCondition" class="btn btn-outline-secondary btn-lg btn-block dropdown-toggle down-in-group3"  type="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'New' %}
        </button>
        <div class="dropdown-menu col-sm-12 text-center">
            {% for choice in form.property_condition.field.choices%}
            <a class="dropdown-item" onclick="selectCondition('{{choice.0}}')">{{choice.1}}</a>
            {% endfor %}
        </div>
    </div>
    <input type="text" class="form-control input-in-group input-lg px-1" id="autocomplete"  placeholder=""
           aria-label="input with three button addons" aria-describedby="button-addon3">
    <div class="input-group-append">
        <button id="submitButton" type="button" class="btn btn-primary button-in-group"><i class="fas fa-search"></i></button>
    </div>
    <!--    <input type="text" id="newField" value="hello">-->
</div>
{% endblock %}
{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC4Gol1U3BbHLkWzeJb5kbggvFAPVKZRAA&libraries=places&region=CO"></script>
<script>
    $("#submitButton").click( function() {
        $("#searchForm").submit();
    });
    function initAutocomplete() {
      // Create the autocomplete object, restricting the search predictions to
      // geographical location types.
      let addressIn = document.getElementById('autocomplete');
      autocomplete = new google.maps.places.Autocomplete(
      addressIn, {types: ['(cities)'], componentRestrictions: {country: 'co'}});
      console.log(autocomplete)
      // Avoid paying for data that you don't need by restricting the set of
      // place fields that are returned to just the address components.
        autocomplete.setFields(['address_components']);
      // When the user selects an address from the drop-down, populate the
      // address fields in the form.

       autocomplete.addListener('place_changed', fillInAddress);
         }

    function fillInAddress() {
      // Get the place details from the autocomplete object.
      var place = autocomplete.getPlace();
        console.log(place)
      for (var i = 0; i < place.address_components.length; i++) {

        var addressType = place.address_components[i].types[0];
        if (addressType === "locality"){
            document.getElementById('id_locality').value = place.address_components[i].long_name ;
         }
        if (addressType === "administrative_area_level_2"){
            document.getElementById('id_city').value = place.address_components[i].long_name;
         }
        if (addressType === "administrative_area_level_1"){
            document.getElementById('id_state').value = place.address_components[i].long_name;
            break;
         }
      }
    }
    function selectBusinessType(choice){
        $('#id_business_type option[value="' + choice +'"]').prop("selected", true);
        document.getElementById('butBusiness').innerHTML = $('#id_business_type option:selected').html();
    };
    function selectPropertyType(choice){
        $('#id_property_type option[value="' + choice +'"]').prop("selected", true);
        document.getElementById('butProperty').innerHTML = $('#id_property_type option:selected').html();
    };
    function selectCondition(choice){
        $('#id_property_condition option[value="' + choice +'"]').prop("selected", true);
        document.getElementById('butCondition').innerHTML = $('#id_property_condition option:selected').html();
    };
    initAutocomplete()
</script>

{% endblock %}